# Generated by Django 6.0.3 on 2026-07-24 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_attachment_chatmessage_attachment_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='channel',
            field=models.CharField(choices=[('all_staff', 'All Staff'), ('team_9', 'Team 9'), ('cs', 'CS Team'), ('market', 'Market Team'), ('corporate', 'Corporate Team'), ('marketing', 'Marketing'), ('accounts', 'Accounts'), ('billing_dispatch', 'Billing Dispatch'), ('tender', 'Tender'), ('quality', 'Quality'), ('collection', 'Collection')], default='all_staff', max_length=30),
        ),
        migrations.CreateModel(
            name='ChatReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('all_staff', 'All Staff'), ('team_9', 'Team 9'), ('cs', 'CS Team'), ('market', 'Market Team'), ('corporate', 'Corporate Team'), ('marketing', 'Marketing'), ('accounts', 'Accounts'), ('billing_dispatch', 'Billing Dispatch'), ('tender', 'Tender'), ('quality', 'Quality'), ('collection', 'Collection')], max_length=30)),
                ('last_read_id', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Read State',
                'verbose_name_plural': 'Chat Read States',
                'unique_together': {('user', 'channel')},
            },
        ),
    ]
