server {
    listen 80;
    server_name YOURDOMAIN.COM www.YOURDOMAIN.COM;

    client_max_body_size 20M;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias /var/www/ferite_steel/staticfiles/;
    }

    location /media/ {
        alias /var/www/ferite_steel/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn/ferite_steel.sock;
        proxy_read_timeout 120s;
    }
}
