# Generated by Django 6.0.3 on 2026-08-01 09:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0020_customer_credit_status_customer_last_assessed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text="Salesperson's free-text notes about the customer.")),
                ('trading_history', models.JSONField(blank=True, help_text='Extracted per-sheet Tally data, plus company-wide and vendor-rank signals.', null=True)),
                ('trading_history_source_filename', models.CharField(blank=True, max_length=255)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('recommendation', models.CharField(choices=[('approve', 'Approve'), ('decline', 'Decline'), ('refer', 'Refer for Review')], max_length=10)),
                ('summary', models.TextField()),
                ('factors', models.JSONField(default=list, help_text="[{'factor', 'detail', 'impact'}]")),
                ('llm_raw_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_assessments', to='database.customer')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_assessments_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Assessment',
                'verbose_name_plural': 'Credit Assessments',
                'ordering': ['-created_at'],
                'permissions': [('can_request_credit_assessment', 'Can request credit assessment')],
            },
        ),
    ]
