# Generated by Django 6.0.3 on 2026-08-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditassessment',
            name='data_confidence',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='How much evidence backed this score (match quality + notes + quotation history).', max_length=10),
        ),
    ]
