# Generated by Django 6.0.3 on 2026-08-07 11:42

import django.core.validators
from django.db import migrations, models


def _mark_existing_rows_done(apps, schema_editor):
    # Every row that existed before this migration was created under the old
    # synchronous-only flow, so it already has a score — it was never
    # "processing" in the new sense. Without this, AddField's default would
    # leave them all incorrectly stuck showing as "Processing" in the UI.
    CreditAssessment = apps.get_model('credit_risk', 'CreditAssessment')
    CreditAssessment.objects.filter(score__isnull=False).update(status='done')


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0002_creditassessment_data_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditassessment',
            name='error_message',
            field=models.TextField(blank=True, help_text='Set when status=failed.'),
        ),
        migrations.AddField(
            model_name='creditassessment',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='processing', max_length=12),
        ),
        migrations.AlterField(
            model_name='creditassessment',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('approve', 'Approve'), ('decline', 'Decline'), ('refer', 'Refer for Review')], max_length=10),
        ),
        migrations.AlterField(
            model_name='creditassessment',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='creditassessment',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='creditassessment',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(_mark_existing_rows_done, migrations.RunPython.noop),
    ]
