# Generated by Django 6.0.3 on 2026-08-28 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0003_creditassessment_error_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_max', models.FloatField(default=3.0, help_text='Max marks for the Competitor Streak category.')),
                ('concentration_max', models.FloatField(default=2.0, help_text="Max marks for the Customer's-Customer Concentration category.")),
                ('turnover_max', models.FloatField(default=2.0, help_text='Max marks for the Sales Turnover category.')),
                ('sales_vs_purchase_max', models.FloatField(default=2.0, help_text='Max marks for the Sales vs Purchases category (see sales_vs_purchase_active).')),
                ('sales_vs_purchase_active', models.BooleanField(default=False, help_text='Sales vs Purchases is built but parked — client to confirm before counting it toward the score. Leave off until then.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credit Scoring Config',
                'verbose_name_plural': 'Credit Scoring Config',
            },
        ),
        migrations.CreateModel(
            name='ListedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('exchange', models.CharField(choices=[('nse', 'NSE'), ('bse', 'BSE'), ('both', 'NSE & BSE')], default='nse', max_length=4)),
            ],
            options={
                'verbose_name': 'Listed Company',
                'verbose_name_plural': 'Listed Companies (NSE/BSE reference)',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='creditassessment',
            name='points_earned',
            field=models.FloatField(blank=True, help_text='Deterministic marks awarded, from services/scoring.py.', null=True),
        ),
        migrations.AddField(
            model_name='creditassessment',
            name='points_possible',
            field=models.FloatField(blank=True, help_text='Deterministic marks possible, given the active categories/weights at assessment time.', null=True),
        ),
        migrations.AddField(
            model_name='creditassessment',
            name='score_breakdown',
            field=models.JSONField(default=list, help_text="[{'category', 'label', 'points', 'max', 'detail'}] — one entry per scoring category."),
        ),
        migrations.AddField(
            model_name='creditassessment',
            name='weight_overrides',
            field=models.JSONField(blank=True, help_text='Per-assessment override of CreditScoringConfig maxes, if set at request time (admin only).', null=True),
        ),
        migrations.AlterField(
            model_name='creditassessment',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Derived from points_earned/points_possible (rounded to a 1-10 scale) — never set directly.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
