# Generated by Django 6.0.3 on 2026-05-13 12:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('transport_extra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loading_rate', models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=8)),
                ('notes', models.TextField(blank=True, help_text='AI context: discount preferences, special terms, etc.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('main', 'Main'), ('rolling', 'Rolling'), ('plate', 'Plate')], max_length=10)),
                ('size', models.CharField(max_length=100)),
                ('pieces', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['type', 'product_name', 'size'],
            },
        ),
    ]
