# Generated by Django 6.0.3 on 2026-05-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='handling_team',
            field=models.CharField(blank=True, choices=[('team_9', 'Team 9'), ('cs', 'CS Team'), ('market', 'Market Team'), ('corporate', 'Corporate Team')], max_length=20),
        ),
    ]
