# Generated by Django 6.0.3 on 2026-05-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_product_sub_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['type', 'sub_type', 'size'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
