# Generated by Django 6.0.3 on 2026-05-20 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_customer_rm'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_product',
            field=models.ForeignKey(blank=True, help_text='If set, effective rate = base product rate + offset below.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_products', to='database.product', verbose_name='Base Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='rate_offset',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Added to the base product rate to get this product's effective rate (₹/T). Ignored if no base product is set.", max_digits=12),
        ),
    ]
