# Generated by Django 6.0.3 on 2026-05-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_rename_make_to_category_add_manufacturer_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'sub_type', 'size'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='msme_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='MSME/Udhyan Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='PAN Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='sap_created_at',
            field=models.DateField(blank=True, null=True, verbose_name='SAP Creation Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='type_of_business',
            field=models.CharField(blank=True, choices=[('C', 'Commercial'), ('I', 'Industrial'), ('G', 'Government')], max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='grade',
            field=models.CharField(blank=True, choices=[('E250', 'E250'), ('E250ER', 'E250ER'), ('E250BO', 'E250BO'), ('E350BR', 'E350BR'), ('E350C', 'E350C'), ('516-GR 60', '516-GR 60'), ('516-GR 70', '516-GR 70'), ('C45', 'C45'), ('513D', '513D'), ('DD', 'DD'), ('FE500', 'FE500'), ('FE500D', 'FE500D'), ('HCRM', 'HCRM'), ('CRS', 'CRS'), ('1018', '1018'), ('EN8', 'EN8'), ('EN9', 'EN9'), ('AZ 70', 'AZ 70'), ('AZ 150', 'AZ 150'), ('AZ 150 C+', 'AZ 150 C+'), ('PPGI', 'PPGI'), ('PPGL', 'PPGL'), ('SHS', 'SHS'), ('IS4923', 'IS4923'), ('IS1161', 'IS1161'), ('SS304', 'SS304'), ('SS316', 'SS316')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, choices=[('6MTR', '6MTR'), ('12MTR', '12MTR'), ('5-6MTR', '5-6MTR'), ('10-12MTR', '10-12MTR'), ('7-12 MTR', '7-12 MTR'), ('2.5MTR', '2.5MTR'), ('8 feet', '8 feet'), ('10 feet', '10 feet'), ('12 feet', '12 feet'), ('14 feet', '14 feet'), ('16 feet', '16 feet'), ('20 feet', '20 feet'), ('2500', '2500'), ('3000', '3000'), ('3150', '3150'), ('5000', '5000'), ('6000', '6000'), ('6300', '6300'), ('8000', '8000'), ('10000', '10000'), ('12000', '12000'), ('CUTSIZE', 'CUTSIZE'), ('Random', 'Random'), ('Other', 'Other')], max_length=50),
        ),
    ]
