# Generated by Django 6.0.3 on 2026-06-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_add_customer_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'permissions': [('can_reassign_customer', 'Can reassign customer')], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
