# Generated by Django 6.0.3 on 2026-06-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_customer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('angle', 'Angle'), ('channel', 'Channel'), ('ub', 'UB'), ('uc', 'UC'), ('beam', 'Beam'), ('flat', 'Flat'), ('red_material', 'Red Material'), ('tmt', 'TMT'), ('pipe', 'Pipe'), ('billet', 'Billet'), ('rail', 'Rail'), ('wire', 'Wire'), ('scrap', 'Scrap')], max_length=20),
        ),
    ]
