# Generated by Django 6.0.3 on 2026-08-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_alter_product_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_status',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_assessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
