# Generated by Django 6.0.3 on 2026-08-21 10:59
# Hand-edited: use RenameField instead of Remove+Add so existing
# customer.notes data survives the migration (a straight RemoveField+AddField
# would drop the column and lose it).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_product_category_others'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='notes',
            new_name='customer_history',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_history',
            field=models.TextField(blank=True, help_text='AI context: discount preferences, special terms, etc.', verbose_name='Customer History'),
        ),
    ]
