# Generated by Django 6.0.3 on 2026-08-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_remove_customer_notes_customer_customer_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='competitors',
            field=models.TextField(blank=True, help_text="One competitor per line, as 'Name - tier' (tier: good/mid/bad, e.g. 'Jindal Steel - good') — used by Credit Risk's Competitor Streak scoring."),
        ),
    ]
