from django.urls import path
from . import views

urlpatterns = [
    path('', views.training_home, name='training_home'),
    path('cases/', views.case_list, name='case_list'),
    path('cases/create/', views.case_create, name='case_create'),
    path('cases/<int:pk>/', views.case_detail, name='case_detail'),
    path('cases/<int:pk>/edit/', views.case_edit, name='case_edit'),
    path('cases/<int:pk>/delete/', views.case_delete, name='case_delete'),
    path('quizzes/', views.quiz_list, name='quiz_list'),
    path('quizzes/attempt/<int:pk>/', views.quiz_results, name='quiz_results'),
    path('quizzes/<int:pk>/', views.quiz_detail, name='quiz_detail'),
    path('quizzes/<int:pk>/take/', views.quiz_take, name='quiz_take'),
    path('documents/', views.document_list, name='document_list'),
    path('documents/create/', views.document_create, name='document_create'),
    path('documents/<int:pk>/', views.document_detail, name='document_detail'),
    path('documents/<int:pk>/delete/', views.document_delete, name='document_delete'),
    path('ask/', views.document_ask, name='document_ask'),
    path('quizzes/create/', views.quiz_set_create, name='quiz_set_create'),
    path('quizzes/<int:pk>/edit/', views.quiz_set_edit, name='quiz_set_edit'),
    path('quizzes/<int:pk>/delete/', views.quiz_set_delete, name='quiz_set_delete'),
    path('questions/practice/<int:pk>/', views.question_practice, name='question_practice'),
    path('questions/<int:pk>/attempts/', views.question_attempts, name='question_attempts'),
    path('questions/', views.question_list, name='question_list'),
    path('quizzes/<int:pk>/attempts/', views.quiz_set_attempts, name='quiz_set_attempts'),
    path('questions/create/', views.question_create, name='question_create'),
    path('questions/create/<int:quiz_pk>/', views.question_create, name='question_create_for_quiz'),
    path('questions/<int:pk>/edit/', views.question_edit, name='question_edit'),
    path('questions/<int:pk>/delete/', views.question_delete, name='question_delete'),
]
