# Generated by Django 6.0.3 on 2026-05-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.CharField(blank=True, choices=[('india_mart', 'India Mart'), ('cs', 'CS Team'), ('market', 'Market Team'), ('corporate', 'Corporate Team')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('lead', 'Team Lead'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
