# Generated by Django 6.0.3 on 2026-05-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0003_rename_india_mart_to_team_9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('lead', 'Team Lead'), ('member', 'Member'), ('primary', 'Primary Member'), ('rolling', 'Rolling Member'), ('loading_dock', 'Loading Dock')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.CharField(blank=True, choices=[('team_9', 'Team 9'), ('cs', 'CS Team'), ('market', 'Market Team'), ('corporate', 'Corporate Team')], max_length=20, null=True),
        ),
    ]
