# Generated by Django 6.0.3 on 2026-06-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0004_alter_customuser_role_alter_customuser_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_manage_users', 'Can manage users'), ('can_view_user_list', 'Can view user list')]},
        ),
    ]
