# Generated by Django 6.0.3 on 2026-06-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
