# Generated by Django 6.0.3 on 2026-08-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0007_customuser_phone_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.CharField(blank=True, choices=[('team_9', 'Team 9'), ('cs', 'CS Team'), ('market', 'Market Team'), ('corporate', 'Corporate Team'), ('marketing', 'Marketing'), ('accounts', 'Accounts'), ('billing_dispatch', 'Billing Dispatch'), ('tender', 'Tender'), ('quality', 'Quality'), ('collection', 'Collection')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('lead_created', 'New Lead'), ('quotation_approved', 'Quotation Approved'), ('quotation_win', 'Quotation Won'), ('quotation_loss', 'Quotation Lost'), ('case_created', 'New Case'), ('market_confirmed', 'Order Confirmed'), ('market_do_pending', 'DO Requested'), ('market_completed', 'Order Completed'), ('credit_high_risk', 'High Credit Risk'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
