# Generated by Django 6.0.3 on 2026-08-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0008_alter_customuser_team_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMApiStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'LLM API Status',
                'verbose_name_plural': 'LLM API Status',
            },
        ),
    ]
