# Generated by Django 6.0.3 on 2026-08-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0009_llmapistatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmapistatus',
            name='email_polling_paused',
            field=models.BooleanField(default=False),
        ),
    ]
