# Generated by Django 6.0.3 on 2026-08-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0010_llmapistatus_email_polling_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmapistatus',
            name='email_polling_resumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
