# Generated by Django 6.0.3 on 2026-05-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_lead_company_lead_industry_lead_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationlineitem',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='quotationlineitem',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='quotationlineitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='quotation',
            name='cgst_percent',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.CharField(default='Advance', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sgst_percent',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='transport_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationlineitem',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotationlineitem',
            name='make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotationlineitem',
            name='pcs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
