# Generated by Django 6.0.3 on 2026-05-11 19:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_remove_quotationlineitem_discount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('transport_extra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loading_rate', models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='parent_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='quotations.quotation'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
