# Generated by Django 6.0.3 on 2026-05-12 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_customer_quotation_parent_quotation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True, help_text='AI context: usual margins, preferred products, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='AI context: discount preferences, special terms, etc.'),
        ),
        migrations.AddField(
            model_name='lead',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='quotations.broker'),
        ),
        migrations.CreateModel(
            name='MarketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_team', models.CharField(choices=[('primary', 'Primary'), ('rolling', 'Rolling')], max_length=20)),
                ('product_details', models.TextField(help_text='What the broker ordered')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('new', 'New Order'), ('rate_sent', 'Rate Sent to Broker'), ('broker_confirmed', 'Broker Confirmed'), ('do_pending', 'DO Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=30)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_sent_at', models.DateTimeField(blank=True, null=True)),
                ('broker_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('do_requested_at', models.DateTimeField(blank=True, null=True)),
                ('do_number', models.CharField(blank=True, max_length=100)),
                ('do_issued_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='quotations.broker')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_orders_created', to=settings.AUTH_USER_MODEL)),
                ('loading_dock_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loading_dock_orders', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_orders', to='quotations.quotation')),
            ],
            options={
                'verbose_name': 'Market Order',
                'verbose_name_plural': 'Market Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
