# Generated by Django 6.0.3 on 2026-05-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_broker_customer_notes_lead_broker_marketorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('main', 'Main'), ('rolling', 'Rolling'), ('plate', 'Plate')], max_length=10)),
                ('size', models.CharField(max_length=100)),
                ('pieces', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['type', 'product_name', 'size'],
            },
        ),
        migrations.DeleteModel(
            name='PricingEntry',
        ),
    ]
