# Generated by Django 6.0.3 on 2026-05-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_product_delete_pricingentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
