# Generated by Django 6.0.3 on 2026-05-13 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_broker'),
        ('quotations', '0007_delete_customer_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='database.broker'),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='database.broker'),
        ),
        migrations.DeleteModel(
            name='Broker',
        ),
    ]
