# Generated by Django 6.0.3 on 2026-05-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_alter_lead_broker_alter_marketorder_broker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='What clients say, e.g. "sariya", "patti", "12mm rod"', max_length=100)),
                ('maps_to', models.CharField(help_text='Canonical product name, e.g. "TMT Bars 12mm"', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product Keyword',
                'verbose_name_plural': 'Product Keywords',
                'ordering': ['keyword'],
            },
        ),
    ]
