# Generated by Django 6.0.3 on 2026-05-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_productkeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('team_9', 'Team 9'), ('cs', 'CS Team'), ('market', 'Market Team'), ('corporate', 'Corporate Team')], max_length=20, unique=True)),
                ('email_address', models.EmailField(help_text='Shared team inbox, e.g. enquiry@ferrite.in', max_length=254)),
                ('imap_host', models.CharField(default='imap.gmail.com', max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('imap_username', models.EmailField(max_length=254)),
                ('imap_password', models.CharField(help_text='Use an App Password, not the account password', max_length=255)),
                ('use_ssl', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Email Config',
                'verbose_name_plural': 'Team Email Configs',
                'ordering': ['team'],
            },
        ),
    ]
