# Generated by Django 6.0.3 on 2026-05-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0010_teamemailconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='payment_terms',
            field=models.CharField(choices=[('Advance', 'Advance'), ('Cash', 'Cash')], default='Advance', max_length=100),
        ),
    ]
