# Generated by Django 6.0.3 on 2026-05-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0011_alter_quotation_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('quoted', 'Quoted'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
