# Generated by Django 6.0.3 on 2026-05-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0012_add_closed_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationlineitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
