# Generated by Django 6.0.3 on 2026-05-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0014_alter_lineitem_length_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationlineitem',
            name='uom',
            field=models.CharField(choices=[('ton', 'T'), ('kg', 'KG')], default='ton', max_length=3),
        ),
        migrations.AlterField(
            model_name='quotationlineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
