# Generated by Django 6.0.3 on 2026-05-19 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_customer_rm'),
        ('quotations', '0015_quotationlineitem_uom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='winning_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_as', to='quotations.quotation'),
        ),
        migrations.AddField(
            model_name='quotationlineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='database.product'),
        ),
    ]
