# Generated by Django 6.0.3 on 2026-05-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0016_quotation_stock_deducted_quotation_winning_quotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationlineitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
