# Generated by Django 6.0.3 on 2026-05-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0017_alter_lineitem_notes_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationlineitem',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
