# Generated by Django 6.0.3 on 2026-05-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0018_quotationlineitem_discount_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='loading_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
