# Generated by Django 6.0.3 on 2026-05-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0019_add_loading_extra_to_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamemailconfig',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, help_text='set automatically after each successful poll', null=True),
        ),
        migrations.AddField(
            model_name='teamemailconfig',
            name='poll_interval_minutes',
            field=models.IntegerField(default=30, help_text='How often to poll this inbox automatically (minutes)'),
        ),
    ]
