# Generated by Django 6.0.3 on 2026-05-26 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0020_teamemailconfig_last_polled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketorder',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_orders', to='quotations.lead'),
        ),
    ]
