# Generated by Django 6.0.3 on 2026-05-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0021_marketorder_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamemailconfig',
            name='smtp_host',
            field=models.CharField(blank=True, default='', help_text='Leave blank to derive from IMAP host (Gmail). Set explicitly for Outlook: smtp.office365.com', max_length=255),
        ),
        migrations.AddField(
            model_name='teamemailconfig',
            name='smtp_port',
            field=models.IntegerField(default=587, help_text='465 for SSL, 587 for STARTTLS (Outlook/M365)'),
        ),
        migrations.AddField(
            model_name='teamemailconfig',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, help_text='Use SSL for SMTP. Off = STARTTLS (required for Outlook/M365)'),
        ),
        migrations.AlterField(
            model_name='teamemailconfig',
            name='use_ssl',
            field=models.BooleanField(default=True, help_text='Enable SSL for IMAP (port 993)'),
        ),
    ]
