# Generated by Django 6.0.3 on 2026-06-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0022_smtp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamemailconfig',
            name='smtp_password',
            field=models.CharField(blank=True, default='', help_text='Leave blank to use imap_password. Required if smtp_username is set.', max_length=255),
        ),
        migrations.AddField(
            model_name='teamemailconfig',
            name='smtp_username',
            field=models.EmailField(blank=True, default='', help_text='Leave blank to use imap_username. Set if sending from a different account (e.g. Outlook) than the inbox (e.g. Gmail)', max_length=254),
        ),
    ]
