# Generated by Django 6.0.3 on 2026-06-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0023_smtp_credentials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketorder',
            options={'ordering': ['-created_at'], 'permissions': [('can_assign_loading_dock', 'Can assign loading dock'), ('can_create_market_order', 'Can create market order'), ('can_update_do', 'Can update DO')], 'verbose_name': 'Market Order', 'verbose_name_plural': 'Market Orders'},
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve_quotation', 'Can approve quotation')], 'verbose_name': 'Quotation', 'verbose_name_plural': 'Quotations'},
        ),
    ]
