# Generated by Django 6.0.3 on 2026-06-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0024_alter_marketorder_options_alter_quotation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_notes_clean',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_notes_raw',
            field=models.TextField(blank=True),
        ),
    ]
