# Generated by Django 6.0.3 on 2026-06-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0025_lead_lead_notes_clean_lead_lead_notes_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamemailconfig',
            name='team',
            field=models.CharField(choices=[('team_9', 'Team 9'), ('cs', 'CS Team'), ('market', 'Market Team'), ('corporate', 'Corporate Team')], max_length=20),
        ),
    ]
