# Generated by Django 6.0.3 on 2026-06-11 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0026_remove_team_email_config_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='received_via',
            field=models.ForeignKey(blank=True, help_text='Email config that received this lead (used to reply from the correct inbox)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='quotations.teamemailconfig'),
        ),
    ]
