# Generated by Django 6.0.3 on 2026-06-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0027_lead_received_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quotation_notes_clean',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_notes_raw',
            field=models.TextField(blank=True),
        ),
    ]
