# Generated by Django 6.0.3 on 2026-06-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0028_quotation_quotation_notes_clean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='sales_order_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
