# Generated by Django 6.0.3 on 2026-07-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0029_add_sales_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='sent_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('email_reply', 'Email - Reply'), ('manual', 'Manual Entry')], max_length=20),
        ),
    ]
