# Generated by Django 6.0.3 on 2026-07-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0030_quotation_sent_message_id_alter_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('manual', 'Manual Entry')], max_length=20),
        ),
    ]
