# Generated by Django 6.0.3 on 2026-07-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0031_alter_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationlineitem',
            name='uom',
            field=models.CharField(choices=[('ton', 'T'), ('kg', 'KG'), ('mtr', 'Mtr'), ('nos', 'Nos')], default='ton', max_length=3),
        ),
    ]
