# Generated by Django 6.0.3 on 2026-08-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0033_quotationlineitem_grade_site_godown'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationlineitem',
            name='addons',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
