# Generated by Django 6.0.3 on 2026-08-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0034_quotationlineitem_addons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationlineitem',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quotationlineitem',
            name='length',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quotationlineitem',
            name='make',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
