# Generated by Django 6.0.3 on 2026-06-10 11:56

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_quizattempt'),
    ]

    operations = [
        VectorExtension(),
    ]
