# Generated by Django 6.0.3 on 2026-06-11 22:23

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_enable_pgvector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgedocument',
            name='file',
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='direct_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='file_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='source_type',
            field=models.CharField(choices=[('file', 'File'), ('text', 'Direct Text')], default='file', max_length=10),
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('chunk_index', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='training.knowledgedocument')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'ordering': ['document', 'chunk_index'],
            },
        ),
    ]
