# Generated by Django 6.0.3 on 2026-06-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_remove_knowledgedocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
